public with sharing class ListCommonObject {
    
    public String championatName  {get; set;}
    public String racerName {get; set;}
    public Double startPosition {get; set;}
    public String status {get; set;}
    public Boolean experienceOnTrack {get; set;}
    public String recordType {get; set;}
    public Decimal yearsInRacing {get; set;}
    public String racerQualification {get; set;}
    public String racerPoints {get; set;}
    public String winBonusAmount {get; set;}
    public Date champDate {get; set;}
    public String champTrack {get; set;}
    public String champCapacity {get; set;}
}
